test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -20,6 +20,18 @@ jobs:
     - name: Checkout code
       uses: actions/checkout@v4
 
+    - name: Inspect project folders
+      run: |
+        echo "🔍 Checking .fvm directory"
+        ls -la .fvm || echo ".fvm folder not found"
+        echo "🔍 Checking .dart_tool directories"
+        ls -la .dart_tool || echo ".dart_tool not found at root"
+        ls -la apps/**/.dart_tool || echo ".dart_tool not found in apps"
+        ls -la packages/**/.dart_tool || echo ".dart_tool not found in packages"
+    
+        echo "🔍 Checking pub-cache"
+        ls -la ~/.pub-cache || echo "pub-cache folder not found"
+
     # Cache FVM (project .fvm + global SDK versions)
     - name: Cache FVM (project + global versions)
       id: fvm-cache
@@ -108,7 +120,3 @@ jobs:
     # Analyze
     - name: Analyze
       run: fvm flutter analyze .
-
-    # Test
-    - name: Run Tests
-      run: fvm flutter test
